name: bizgame
favicon: null
layout_spectrum: 0.8174897450953722
typography_spectrum: 0.3860883852466941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2090917679015547
  lightness: 0.020323966396972537
  saturation: 0.23688678699545562
  rhythmicContrast: 0.905853787669912
purpose: []
