name: bizgame
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2753d7'
    - '#bfccf3'
    - '#00a86b'
    - '#ffffff'
    - '#5fc8a2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
