name: bizgame
favicon: null
layout_spectrum: 0.8174897450953722
typography_spectrum: 0.3860883852466941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2753d7'
    - '#bfccf3'
    - '#00a86b'
    - '#ffffff'
    - '#5fc8a2'
  brandStrength: 0.5625
  lightness: 0.020323966396972537
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
